name: code-review

services:
  agent:
    build: .
    environment:
      - GITLAB_HOST=
      - TOKEN=
      - GROUP_ID=
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    command: ./entrypoint.sh
